### ISSUE TITLE
Considering integrating StreamPipes and DSS?

### ISSUE THREAD

**Issue by peacewong** [apache/incubator-streampipes#10]
Apache StreamPipes is a very great project in the field of tream processing frameworks, and I think it is a good way to enhance the influence of our two projects is by integrating StreamPipes with DataSphere Studio.
DataSphere Studio is a one-stop data application development and management portal open source by WeBank, which meets the needs of the entire process of data application development from data exchange, desensitization and cleaning, analysis and mining, quality inspection, visual display, regular scheduling to data output.
Github address: https://github.com/WeBankFinTech/DataSphereStudio

**Comment by tenthe** [comment]
Hi, thank you very much for the suggestion. I had a look at the project and I think an integration would be great.
Do you have any suggestions how the integration could look like?  I think it would be cool to have Adapters and Sinks in StreamPipes for DataSphereStudio.

**Comment by dominikriemer** [comment]
Moved to Apache StreamPipes Jira: https://issues.apache.org/jira/projects/STREAMPIPES/issues/STREAMPIPES-62
