### ISSUE TITLE
Error when installing W10

### ISSUE THREAD

**Issue by alexmc1510** [apache/incubator-streampipes#8]
Dear team,

When I try to install ".bat" in W10 I receive the following error:

C:\Users\TA-INDUS-C41581\Desktop\streampipes-installer-master\streampipes\windows10>streampipes.bat start
& : No se puede cargar el archivo
C:\Users\TA-INDUS-C41581\Desktop\streampipes-installer-master\streampipes\windows10\streampipes.ps1. El archivo
C:\Users\TA-INDUS-C41581\Desktop\streampipes-installer-master\streampipes\windows10\streampipes.ps1 no está firmado
digitalmente. No se puede ejecutar este script en el sistema actual. Para obtener más información acerca de la
ejecución de scripts y la configuración de la directiva de ejecución, consulta about_Execution_Policies en
https:/go.microsoft.com/fwlink/?LinkID=135170.
En línea: 1 Carácter: 3
+ & 'C:\Users\TA-INDUS-C41581\Desktop\streampipes-installer-master\stre ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

I have tried to modify this policy but I receive this error:
Set-ExecutionPolicy : Windows PowerShell actualizó la directiva de ejecución correctamente, pero el valor queda
invalidado por una directiva definida en un ámbito más específico. Debido a esta invalidación, el shell mantendrá la
directiva de ejecución efectiva actual: RemoteSigned. Escriba "Get-ExecutionPolicy -List" para ver la configuración de
la directiva de ejecución. Para obtener más información, vea "Get-Help Set-ExecutionPolicy".
En línea: 1 Carácter: 1
+ Set-ExecutionPolicy "Unrestricted" -Scope CurrentUser -Confirm:$false
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand

Could you help me?

REgards

**Comment by dominikriemer** [comment]
This seems to be an issue with a security policy...can you try to run StreamPipes manually?

- From the templates folder, copy the .env and one of the two docker-compose files to the windows10 folder
- In the windows10 folder, rename the docker compose (e.g., move docker-compose.lite.yml docker-compose.yml)
- In the windows10 folder, open the .env file and set SP_HOST and SP_KAFKA_HOST according to your hostname or IP address (if you don't have a static IP, use host.docker.internal as hostname)
- run `docker-compose up -d` to start StreamPipes

Tell me if you still have problems!

**Comment by alexmc1510** [comment]
Hello, thank you for your support and sorry for the delay, I was out of home.
I have tried to run docker-compose but I receive the following error regarding kafka image:
```
Status: Downloaded newer image for wurstmeister/kafka:2.12-2.2.0
ERROR: no such image: backend:: invalid reference format
```
Sorry but docker for me is sometething new.

Regards,

**Comment by dominikriemer** [comment]
No problem, we're here to help ;-)
Can you please double-check that you copied both the docker-compose.yml and the .env file?
The error you get suggests that the env file is missing in the directory where the docker-compose.yml is located.
